### PR TITLE
Use std::os::unix::net::UnixStream::pair instead of rustix::net::socketpair

### PR DESCRIPTION
**Pull request by teohhanhui**
Small follow-up to #1

### CODE REVIEW

**Comment by slp** [comment]
@teohhanhui hm... why do we need to switch from `socketpair` to `UnixStream::pair` (I don't have a preference, I'm just wondering why)

**Comment by teohhanhui** [comment]
Just using `std` as much as possible. More battle tested etc... Also, `UnixStream` is a higher level wrapper, even though we're just directly converting it into `OwnedFd` haha...

**Comment by teohhanhui** [comment]
@slp Any outstanding concerns here?

**Comment by slp** [comment]
> @slp Any outstanding concerns here?

Could you please add a `Signed-off-by` line to the commit?

**Comment by teohhanhui** [comment]
Done.

**Review by slp — APPROVED** [review]
Thanks!

**Pull request merged**
